# Generated by Django 5.2.8 on 2025-12-03 06:57

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('payin_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID for the payin', unique=True)),
                ('code', models.CharField(blank=True, help_text='Unique code for the payin (e.g., rnDPx, rW5ao)', max_length=50, null=True, unique=True)),
                ('pay_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Requested payment amount', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('confirmed_amount', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Confirmed payment amount', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('user', models.CharField(blank=True, help_text='User ID making the payment', max_length=255, null=True)),
                ('merchant_order_id', models.UUIDField(help_text="Merchant's order ID (UUID)")),
                ('bank', models.CharField(help_text='Bank name or identifier (e.g., ftd, iobper-alex)', max_length=255)),
                ('utr', models.CharField(blank=True, help_text='Unique Transaction Reference from bank', max_length=255, null=True)),
                ('user_submitted_utr', models.CharField(blank=True, help_text='UTR submitted by the user', max_length=255, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('assigned', 'Assigned'), ('success', 'Success'), ('dropped', 'Dropped'), ('dispute', 'Dispute'), ('duplicate', 'Duplicate')], default='initiated', help_text='Current status of the payin', max_length=20)),
                ('duration', models.DurationField(blank=True, help_text='Duration taken for payment processing', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments', null=True)),
                ('assigned_at', models.DateTimeField(blank=True, help_text='Time when the payin was assigned', null=True)),
                ('merchant', models.ForeignKey(help_text='Merchant associated with this payin', on_delete=django.db.models.deletion.PROTECT, related_name='payins', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Payin',
                'verbose_name_plural': 'Payins',
                'db_table': 'payins',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payin_uuid'], name='payins_payin_u_abcd72_idx'), models.Index(fields=['code'], name='payins_code_0aa8ac_idx'), models.Index(fields=['merchant_order_id'], name='payins_merchan_193734_idx'), models.Index(fields=['status'], name='payins_status_077fab_idx'), models.Index(fields=['-created_at'], name='payins_created_34ecff_idx')],
            },
        ),
    ]
