# Generated by Django 5.2.8 on 2026-03-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payin',
            name='merchant_order_id',
            field=models.UUIDField(help_text="Merchant's order ID (UUID, unique per payin)", unique=True),
        ),
    ]
