# Generated by Django 5.2.8 on 2025-11-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payin',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('assigned', 'Assigned'), ('success', 'Success'), ('dropped', 'Dropped'), ('dispute', 'Dispute'), ('duplicate', 'Duplicate')], default='initiated', help_text='Current status of the payin', max_length=20),
        ),
    ]
