# Generated by Django 5.2.8 on 2026-05-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0002_alter_payin_merchant_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payin',
            name='utr_submitted_at',
            field=models.DateTimeField(blank=True, help_text='Time when the UTR was submitted by the user', null=True),
        ),
    ]
