# Generated by Django 5.2.8 on 2025-11-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0002_alter_payin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payin',
            name='user',
            field=models.CharField(blank=True, help_text='User ID making the payment', max_length=255, null=True, unique=True),
        ),
    ]
