# Generated by Django 5.2.8 on 2025-11-28 10:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0003_alter_payin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payin',
            name='pay_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Requested payment amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
