# Generated by Django 5.2.8 on 2025-11-28 10:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0006_alter_payin_confirmed_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payin',
            name='confirmed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Confirmed payment amount', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='payin',
            name='pay_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Requested payment amount', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
