# Generated by Django 5.2.8 on 2025-11-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0007_alter_payin_confirmed_amount_alter_payin_pay_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payin',
            name='agent',
        ),
    ]
