# Generated by Django 5.2.8 on 2025-11-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0008_remove_payin_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payin',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='Time when the payin was assigned', null=True),
        ),
    ]
