# Generated by Django 5.2.8 on 2025-11-24 16:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(help_text='Merchant name', max_length=255)),
                ('code', models.CharField(help_text='Unique merchant code', max_length=100, unique=True)),
                ('site', models.URLField(help_text='Merchant site URL', max_length=500)),
                ('api_key', models.CharField(help_text='API key for merchant', max_length=255, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current balance', max_digits=15)),
                ('payin_min', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum payin amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payin_max', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum payin amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payin_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Payin commission percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('payout_min', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum payout amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payout_max', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum payout amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payout_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Payout commission percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('test_mode', models.BooleanField(default=False, help_text='Enable test mode')),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
                'db_table': 'merchants',
                'ordering': ['-created_at'],
            },
        ),
    ]
