# Generated by Django 5.2.8 on 2025-12-03 06:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('nickname', models.CharField(help_text='Nickname for this bank account', max_length=255)),
                ('account_holder_name', models.CharField(help_text="Bank account holder's name", max_length=255)),
                ('account_number', models.CharField(help_text='16 digit account number', max_length=16)),
                ('ifsc_code', models.CharField(help_text='16 digit IFSC code', max_length=16)),
                ('upi_id', models.CharField(blank=True, help_text='UPI ID for this bank account', max_length=255, null=True)),
                ('min_payin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum payin amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_payin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum payin amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current account balance', max_digits=15)),
                ('transaction_count', models.IntegerField(default=0, help_text='Number of transactions')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this bank account is enabled')),
                ('is_qr', models.BooleanField(default=False, help_text='Whether QR code is enabled for this account')),
                ('is_bank', models.BooleanField(default=False, help_text='Whether bank transfer is enabled')),
                ('status', models.BooleanField(default=True, help_text='Account status (active/inactive)')),
                ('last_scheduled_at', models.DateTimeField(blank=True, help_text='Last scheduled transaction time (IST)', null=True)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'db_table': 'bank_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(help_text='Merchant name', max_length=255)),
                ('code', models.CharField(help_text='Unique merchant code', max_length=100, unique=True)),
                ('site', models.URLField(help_text='Merchant site URL', max_length=500)),
                ('return_url', models.URLField(blank=True, help_text='Return URL for merchant', max_length=500, null=True)),
                ('callback_url', models.URLField(blank=True, help_text='Callback URL for merchant', max_length=500, null=True)),
                ('payout_callback_url', models.URLField(blank=True, help_text='Payout callback URL for merchant', max_length=500, null=True)),
                ('api_key', models.CharField(blank=True, help_text='API key for merchant (auto-generated)', max_length=255, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current balance', max_digits=15)),
                ('payin_min', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum payin amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payin_max', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum payin amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payin_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Payin commission percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('payout_min', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum payout amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payout_max', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum payout amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payout_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Payout commission percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('test_mode', models.BooleanField(default=False, help_text='Enable test mode')),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
                'db_table': 'merchants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('amount', models.PositiveIntegerField(help_text='Amount of the transaction')),
                ('utr', models.CharField(help_text='UTR of the transaction', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation time')),
                ('is_used', models.BooleanField(default=False, help_text='Whether the transaction has been used')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_transactions', to='merchants.bankaccount')),
            ],
            options={
                'verbose_name': 'Extracted Transaction',
                'verbose_name_plural': 'Extracted Transactions',
                'db_table': 'extracted_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='merchant',
            field=models.ForeignKey(help_text='Merchant associated with this bank account', on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='merchants.merchant'),
        ),
    ]
