# Generated by Django 5.2.8 on 2025-12-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether this bank account is approved by super admin'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='login_type',
            field=models.CharField(choices=[('normal', 'Normal Login'), ('corp', 'Corporate Login')], default='normal', help_text='Type of login (normal or corporate)', max_length=20),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='netbanking_url',
            field=models.URLField(blank=True, help_text='URL for netbanking login', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='password',
            field=models.CharField(blank=True, help_text='Netbanking password', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='username',
            field=models.CharField(blank=True, help_text='Netbanking username', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='username2',
            field=models.CharField(blank=True, help_text='Second username for corporate login', max_length=255, null=True),
        ),
    ]
