# Generated by Django 5.2.8 on 2025-11-27 16:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('nickname', models.CharField(help_text='Nickname for this bank account', max_length=255)),
                ('account_holder_name', models.CharField(help_text="Bank account holder's name", max_length=255)),
                ('account_number', models.CharField(help_text='16 digit account number', max_length=16)),
                ('ifsc_code', models.CharField(help_text='16 digit IFSC code', max_length=16)),
                ('upi_id', models.CharField(blank=True, help_text='UPI ID for this bank account', max_length=255, null=True)),
                ('min_payin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum payin amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_payin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum payin amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current account balance', max_digits=15)),
                ('transaction_count', models.IntegerField(default=0, help_text='Number of transactions')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this bank account is enabled')),
                ('is_qr', models.BooleanField(default=False, help_text='Whether QR code is enabled for this account')),
                ('is_intent', models.BooleanField(default=False, help_text='Whether intent payment is enabled')),
                ('is_bank', models.BooleanField(default=False, help_text='Whether bank transfer is enabled')),
                ('status', models.BooleanField(default=True, help_text='Account status (active/inactive)')),
                ('last_scheduled_at', models.DateTimeField(blank=True, help_text='Last scheduled transaction time (IST)', null=True)),
                ('merchant', models.ForeignKey(help_text='Merchant associated with this bank account', on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'db_table': 'bank_accounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
