# Generated by Django 5.2.8 on 2025-12-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_bankaccount_is_approved_bankaccount_login_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='status',
            field=models.BooleanField(default=False, help_text='Account status (active/inactive)'),
        ),
    ]
