# Generated by Django 5.2.8 on 2025-11-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='callback_url',
            field=models.URLField(blank=True, help_text='Callback URL for merchant', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='payout_callback_url',
            field=models.URLField(blank=True, help_text='Payout callback URL for merchant', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='return_url',
            field=models.URLField(blank=True, help_text='Return URL for merchant', max_length=500, null=True),
        ),
    ]
