# Generated by Django 5.2.8 on 2025-11-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_merchant_callback_url_merchant_payout_callback_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key for merchant (auto-generated)', max_length=255, unique=True),
        ),
    ]
