# Generated by Django 5.2.8 on 2025-12-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_alter_bankaccount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank_type',
            field=models.CharField(choices=[('iob', 'Indian Overseas Bank (IOB)'), ('sbi', 'State Bank of India (SBI)'), ('hdfc', 'HDFC Bank'), ('icici', 'ICICI Bank'), ('axis', 'Axis Bank'), ('kotak', 'Kotak Mahindra Bank'), ('pnb', 'Punjab National Bank (PNB)'), ('bob', 'Bank of Baroda (BOB)'), ('canara', 'Canara Bank'), ('union', 'Union Bank of India'), ('idbi', 'IDBI Bank'), ('yes', 'Yes Bank'), ('indusind', 'IndusInd Bank'), ('federal', 'Federal Bank'), ('rbl', 'RBL Bank'), ('other', 'Other')], default='iob', help_text='Type of bank (used to select appropriate bot)', max_length=20),
        ),
    ]
