# Generated by Django 5.2.8 on 2025-12-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_bankaccount_bank_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedtransactions',
            name='is_used',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the transaction has been used'),
        ),
        migrations.AlterField(
            model_name='extractedtransactions',
            name='utr',
            field=models.CharField(db_index=True, help_text='UTR of the transaction', max_length=255),
        ),
        migrations.AddIndex(
            model_name='extractedtransactions',
            index=models.Index(fields=['utr', 'is_used'], name='extracted_t_utr_e49f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedtransactions',
            index=models.Index(fields=['bank_account', 'utr'], name='extracted_t_bank_ac_7c9b18_idx'),
        ),
    ]
