# Generated by Django 5.2.8 on 2025-11-30 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_alter_merchant_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('amount', models.PositiveIntegerField(help_text='Amount of the transaction')),
                ('utr', models.CharField(help_text='UTR of the transaction', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation time')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_transactions', to='merchants.bankaccount')),
            ],
            options={
                'verbose_name': 'Extracted Transaction',
                'verbose_name_plural': 'Extracted Transactions',
                'db_table': 'extracted_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
