# Generated by Django 5.2.8 on 2025-11-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0005_extractedtransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedtransactions',
            name='is_used',
            field=models.BooleanField(default=False, help_text='Whether the transaction has been used'),
        ),
    ]
