# Generated by Django 5.2.8 on 2025-12-16 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0005_alter_extractedtransactions_is_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedtransactions',
            name='merchant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='extracted_transactions', to='merchants.merchant'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='extractedtransactions',
            index=models.Index(fields=['merchant', 'utr'], name='extracted_t_merchan_db80b3_idx'),
        ),
    ]
