# Generated by Django 5.2.8 on 2026-01-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0006_extractedtransactions_merchant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_type',
            field=models.CharField(choices=[('iob', 'Indian Overseas Bank (IOB)'), ('cub', 'City Union Bank (CUB)')], default='iob', help_text='Type of bank (used to select appropriate bot)', max_length=20),
        ),
    ]
