# Generated by Django 5.2.8 on 2026-01-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0007_update_bank_type_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='payout_callback_url',
        ),
    ]
