# Generated by Django 5.2.8 on 2026-05-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0008_remove_merchant_payout_callback_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedtransactions',
            name='used_at',
            field=models.DateTimeField(blank=True, help_text='Time when the transaction was used', null=True),
        ),
    ]
