# Generated by Django 5.2.8 on 2025-12-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_is_active'),
        ('merchants', '0006_extractedtransactions_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='merchants',
            field=models.ManyToManyField(blank=True, help_text='Merchants this user can access', related_name='users', to='merchants.merchant'),
        ),
    ]
