# Generated by Django 5.2.8 on 2025-12-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_merchants_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('transactions', 'Transactions'), ('merchant', 'Merchant'), ('vendor', 'Vendor'), ('customer_service', 'Customer Service'), ('operations', 'Operations'), ('agent', 'Agent')], max_length=255),
        ),
    ]
