# Generated by Django 5.2.8 on 2025-12-08 16:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0004_bankaccount_bank_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('nickname', models.CharField(help_text='Nickname for this settlement account', max_length=255)),
                ('instrument_type', models.CharField(choices=[('bank', 'Bank Transfer'), ('crypto', 'Cryptocurrency')], default='bank', help_text='Type of settlement instrument', max_length=20)),
                ('account_holder_name', models.CharField(blank=True, help_text="Bank account holder's name", max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, help_text='Bank account number', max_length=20, null=True)),
                ('ifsc_code', models.CharField(blank=True, help_text='IFSC code', max_length=11, null=True)),
                ('crypto_wallet_address', models.CharField(blank=True, help_text='Cryptocurrency wallet address', max_length=255, null=True)),
                ('crypto_network', models.CharField(blank=True, help_text='Cryptocurrency network (e.g., ERC20, TRC20, BEP20)', max_length=50, null=True)),
                ('merchant', models.ForeignKey(help_text='Merchant associated with this settlement account', on_delete=django.db.models.deletion.CASCADE, related_name='settlement_accounts', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Settlement Account',
                'verbose_name_plural': 'Settlement Accounts',
                'db_table': 'settlement_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Settlement amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Settlement status', max_length=20)),
                ('method', models.CharField(choices=[('bank', 'Bank Transfer'), ('crypto', 'Cryptocurrency')], default='bank', help_text='Settlement method used', max_length=20)),
                ('bank_account_holder_name', models.CharField(blank=True, help_text='Account holder name (snapshot)', max_length=255, null=True)),
                ('bank_account_number', models.CharField(blank=True, help_text='Account number (snapshot)', max_length=20, null=True)),
                ('bank_ifsc_code', models.CharField(blank=True, help_text='IFSC code (snapshot)', max_length=11, null=True)),
                ('reference_id', models.CharField(blank=True, help_text='External reference ID (UTR, transaction hash, etc.)', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('merchant', models.ForeignKey(help_text='Merchant for this settlement', on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='merchants.merchant')),
                ('settlement_account', models.ForeignKey(blank=True, help_text='Settlement account used for this settlement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='settlements.settlementaccount')),
            ],
            options={
                'verbose_name': 'Settlement',
                'verbose_name_plural': 'Settlements',
                'db_table': 'settlements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='settlements_status_18dd5a_idx'), models.Index(fields=['merchant'], name='settlements_merchan_df3a89_idx'), models.Index(fields=['created_at'], name='settlements_created_ef87fe_idx')],
            },
        ),
    ]
