# Generated by Django 5.2.8 on 2025-12-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='reference_id',
            field=models.CharField(blank=True, help_text='External reference ID (UTR, transaction hash, etc.)', max_length=255, null=True, unique=True),
        ),
    ]
