# Generated by Django 5.2.8 on 2025-12-16 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0002_alter_settlement_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='to_settlement_account',
            field=models.ForeignKey(blank=True, help_text='Destination settlement account (to)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_received', to='settlements.settlementaccount'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='settlement_account',
            field=models.ForeignKey(blank=True, help_text='Settlement account used for this settlement (from)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='settlements.settlementaccount'),
        ),
    ]
