# Generated by Django 5.2.8 on 2025-12-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0003_add_to_settlement_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementaccount',
            name='account_type',
            field=models.CharField(choices=[('from', 'From Account (Source)'), ('to', 'To Account (Destination)')], default='from', help_text='Whether this account is used as source (from) or destination (to)', max_length=10),
        ),
    ]
